name: Deploy AWS Glue Scripts to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "aws_glue_scripts/**"

jobs:
  upload-glue-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Meta Glue Scripts
        run: |
          aws s3 sync aws_glue_scripts/meta/ \
          "s3://glue-etl-job-7249/Etl on meta/scripts/"

      - name: Upload Review Glue Scripts
        run: |
          aws s3 sync aws_glue_scripts/review/ \
          "s3://glue-etl-job-7249/ETL on Review/scripts/"
