name: Deploy AWS Glue Scripts to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "aws_glue_scripts/**"

jobs:
  upload-glue-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------- META ----------
      - name: Upload Meta Glue Script (force rename)
        run: |
          META_FILE=$(ls aws_glue_scripts/meta/*.py | head -n 1)
          aws s3 cp "$META_FILE" \
          "s3://glue-etl-job-7249/Etl on meta/scripts/ETL on meta.py"

      # ---------- REVIEW ----------
      - name: Upload Review Glue Script (force rename)
        run: |
          REVIEW_FILE=$(ls aws_glue_scripts/review/*.py | head -n 1)
          aws s3 cp "$REVIEW_FILE" \
          "s3://glue-etl-job-7249/ETL on Review/scripts/ETL on Reviews.py"

      # ---------- RUN GLUE JOBS ----------
      - name: Run Meta Glue Job
        run: |
          aws glue start-job-run \
            --job-name "ETL on Meta"

      - name: Run Review Glue Job
        run: |
          aws glue start-job-run \
            --job-name "ETL on Reviews"
